unbind r
bind r source-file "$HOME/.tmux.conf"

set-option -g status-position top
set -g prefix C-s
set -g mouse on

# Failed to get shift-return to emit new lines in Claude inside a tmux pane
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Seem not necessary
# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R

# bind -n C-k send-keys -R \; send-keys C-l \; clear-history

bind | split-window -hf

# TODO: Not sure if this is working well
# set-hook -g after-kill-pane 'select-layout -E'

# Ctrl+k without prefix, clear screen + scrollback
#bind-key -n -k send-keys C-l \; send-keys -R \; clear-history

#set -g history-limit 10000

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
